set_property PACKAGE_PIN AE13 [get_ports clk]
set_property PACKAGE_PIN AA13 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property LOC MMCME2_ADV_X0Y4 [get_cells mmcm_i]
set_property LOC BUFGCTRL_X0Y16 [get_cells g[0].bufg_i]
set_property LOC BUFGCTRL_X0Y17 [get_cells g[1].bufg_i]
set_property LOC BUFGCTRL_X0Y18 [get_cells g[2].bufg_i]
set_property LOC BUFGCTRL_X0Y19 [get_cells g[3].bufg_i]
set_property LOC BUFGCTRL_X0Y20 [get_cells g[4].bufg_i]
set_property LOC BUFGCTRL_X0Y21 [get_cells g[5].bufg_i]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets -of_objects [get_pins mmcm_i/CLKIN1]]
create_clock -period 10 [get_ports clk]
